const menuToggle=document.getElementById("menuToggle"),mainNav=document.getElementById("mainNav");
if(menuToggle&&mainNav){menuToggle.addEventListener("click",()=>{const open=mainNav.classList.toggle("open");menuToggle.setAttribute("aria-expanded",String(open));menuToggle.setAttribute("aria-label",open?"Close navigation":"Open navigation")});mainNav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{mainNav.classList.remove("open");menuToggle.setAttribute("aria-expanded","false")}))}
const year=document.getElementById("year");if(year)year.textContent=String(new Date().getFullYear());
const workspace=document.getElementById("workspace"),workspaceTitle=document.getElementById("workspaceTitle"),workspaceBody=document.getElementById("workspaceBody"),toolMessage=document.getElementById("toolMessage");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const field=(label,id,placeholder="",type="text")=>'<label class="tool-label" for="'+id+'">'+label+'</label><input class="tool-input" id="'+id+'" type="'+type+'" placeholder="'+placeholder+'">';
const area=(label,id,placeholder="")=>'<label class="tool-label" for="'+id+'">'+label+'</label><textarea class="tool-input" id="'+id+'" rows="6" placeholder="'+placeholder+'"></textarea>';
const btn=(id,label)=>'<button class="button primary" id="'+id+'" type="button">'+label+'</button>';
function openTool(name){workspace.hidden=false;toolMessage.textContent="";let html="",title="";
if(name==="writing"){title="Writing Helper";html='<p class="tool-help">Create a useful brief you can paste into your preferred writing tool. This page does not connect to an AI model.</p>'+field("What are you writing?","wrGoal","e.g. a project update email")+field("Audience","wrAudience","e.g. a customer or manager")+ '<label class="tool-label" for="wrTone">Tone</label><select class="tool-input" id="wrTone"><option>Clear and professional</option><option>Friendly and conversational</option><option>Persuasive</option><option>Concise</option><option>Academic</option></select>'+area("Key points to include","wrPoints","List the important details") +btn("makeBrief","Create brief")+'<div id="briefOutput" class="tool-output" hidden></div>'}
if(name==="formatter"){title="Text Formatter";html='<p class="tool-help">Text is processed in your browser. Choose a transformation, then copy the result.</p>'+area("Your text","fmtInput","Paste or type text here")+'<div class="tool-actions"><button class="button secondary" id="fmtTrim">Clean spaces</button><button class="button secondary" id="fmtSentence">Sentence case</button><button class="button secondary" id="fmtUpper">UPPERCASE</button><button class="button secondary" id="fmtLower">lowercase</button></div>'+area("Result","fmtOutput","Your formatted text appears here")+btn("fmtCopy","Copy result")}
if(name==="converter"){title="Unit Converter";html='<p class="tool-help">Choose a category and units to convert.</p><label class="tool-label" for="convType">Category</label><select class="tool-input" id="convType"><option value="length">Length</option><option value="weight">Weight</option><option value="temp">Temperature</option></select>'+field("Amount","convAmount","Enter a number","number")+'<div class="tool-row">'+ '<div><label class="tool-label" for="convFrom">From</label><select class="tool-input" id="convFrom"></select></div><div><label class="tool-label" for="convTo">To</label><select class="tool-input" id="convTo"></select></div></div>'+btn("convertNow","Convert")+'<div id="convOutput" class="tool-output" aria-live="polite"></div>'}
if(name==="json"){title="JSON Helper";html='<p class="tool-help">Validate and pretty-print JSON locally. Do not paste passwords, API keys or other secrets.</p>'+area("JSON input","jsonInput",'{ "hello": "world" }')+'<div class="tool-actions">'+btn("jsonFormat","Validate & format")+'<button class="button secondary" id="jsonMinify">Minify</button></div>'+area("Result","jsonOutput","Formatted JSON appears here")+btn("jsonCopy","Copy result")}
if(name==="security"){title="Password Tips";html='<p class="tool-help">For your safety, do not type or paste your real password here. This tool gives general guidance only.</p><div class="security-card"><h3>Build a stronger passphrase</h3><ul><li>Use 4–5 unrelated words or a long unique passphrase.</li><li>Use a different password for every account.</li><li>Store passwords in a reputable password manager.</li><li>Enable two-factor authentication when available.</li><li>Never share passwords or one-time codes with anyone.</li></ul><p><strong>Tip:</strong> Length and uniqueness matter more than predictable substitutions like “@” for “a”.</p></div>'}
if(name==="planner"){title="Time Planner";html='<p class="tool-help">Create a temporary task list for this visit. It is not saved after you close or refresh the page.</p>'+field("Task name","taskName","e.g. review project notes")+field("Estimated minutes","taskMinutes","25","number")+btn("addTask","Add task")+'<div class="planner-summary" id="plannerSummary">0 tasks · 0 minutes</div><ul id="taskList" class="task-list"></ul><button class="button secondary" id="clearTasks" type="button">Clear list</button>'}
workspaceTitle.textContent=title;workspaceBody.innerHTML=html;workspace.scrollIntoView({behavior:"smooth",block:"start"});wireTool(name)}
function message(t){toolMessage.textContent=t}
async function copyText(id){const el=document.getElementById(id);if(!el||!el.value){message("There is no result to copy yet.");return}try{await navigator.clipboard.writeText(el.value);message("Copied to clipboard.")}catch(e){el.select();message("Text selected. Use your device's Copy command.")}}
function wireTool(name){
if(name==="writing"){document.getElementById("makeBrief").onclick=()=>{const g=document.getElementById("wrGoal").value.trim(),a=document.getElementById("wrAudience").value.trim(),t=document.getElementById("wrTone").value,p=document.getElementById("wrPoints").value.trim();if(!g){message("Please describe what you are writing.");return}const out="Writing brief\nGoal: "+g+"\nAudience: "+(a||"Not specified")+"\nTone: "+t+"\nKey points:\n"+(p||"Add key points here")+"\n\nInstructions: Draft a clear, accurate response. Do not invent facts. Ask for clarification where details are missing. Review the final text before using it.";const box=document.getElementById("briefOutput");box.hidden=false;box.textContent=out;message("Brief created. This is a prompt/brief, not AI-generated writing.")}}
if(name==="formatter"){const input=()=>document.getElementById("fmtInput").value;const out=v=>document.getElementById("fmtOutput").value=v;document.getElementById("fmtTrim").onclick=()=>out(input().replace(/\r/g,"").split("\n").map(x=>x.replace(/[ \t]+/g," ").trim()).join("\n").replace(/\n{3,}/g,"\n\n").trim());document.getElementById("fmtUpper").onclick=()=>out(input().toUpperCase());document.getElementById("fmtLower").onclick=()=>out(input().toLowerCase());document.getElementById("fmtSentence").onclick=()=>out(input().toLowerCase().replace(/(^|[.!?]\s+)([a-z])/g,(m,a,b)=>a+b.toUpperCase()));document.getElementById("fmtCopy").onclick=()=>copyText("fmtOutput")}
if(name==="converter"){const units={length:{m:1,km:1000,cm:.01,mm:.001,mi:1609.344,ft:.3048,in:.0254},weight:{kg:1,g:.001,lb:.45359237,oz:.028349523125},temp:{C:1,F:1,K:1}};const type=document.getElementById("convType"),from=document.getElementById("convFrom"),to=document.getElementById("convTo");function fill(){const keys=Object.keys(units[type.value]);from.innerHTML=keys.map(k=>'<option value="'+k+'">'+k+'</option>').join("");to.innerHTML=keys.map((k,i)=>'<option value="'+k+'" '+(i===1?'selected':'')+'>'+k+'</option>').join("");if(type.value==="temp"){from.innerHTML=["C","F","K"].map(k=>'<option>'+k+'</option>').join("");to.innerHTML=["C","F","K"].map((k,i)=>'<option '+(i===1?'selected':'')+'>'+k+'</option>').join("")}}type.onchange=fill;fill();document.getElementById("convertNow").onclick=()=>{const v=Number(document.getElementById("convAmount").value);if(!Number.isFinite(v)||document.getElementById("convAmount").value===""){message("Enter a valid number.");return}let base,result;if(type.value==="temp"){base=from.value==="C"?v:from.value==="F"?(v-32)*5/9:v-273.15;result=to.value==="C"?base:to.value==="F"?base*9/5+32:base+273.15}else{base=v*units[type.value][from.value];result=base/units[type.value][to.value]}document.getElementById("convOutput").textContent=v+" "+from.value+" = "+Number(result.toPrecision(10))+" "+to.value;message("")}}
if(name==="json"){const parse=()=>{try{const obj=JSON.parse(document.getElementById("jsonInput").value);document.getElementById("jsonOutput").value=JSON.stringify(obj,null,2);message("Valid JSON.");return obj}catch(e){message("Invalid JSON: "+e.message);return null}};document.getElementById("jsonFormat").onclick=parse;document.getElementById("jsonMinify").onclick=()=>{try{document.getElementById("jsonOutput").value=JSON.stringify(JSON.parse(document.getElementById("jsonInput").value));message("Valid JSON minified.")}catch(e){message("Invalid JSON: "+e.message)}};document.getElementById("jsonCopy").onclick=()=>copyText("jsonOutput")}
if(name==="planner"){const tasks=[];const render=()=>{const list=document.getElementById("taskList");list.innerHTML="";tasks.forEach((t,i)=>{const li=document.createElement("li");li.innerHTML='<span></span><button type="button" aria-label="Remove task">Remove</button>';li.querySelector("span").textContent=t.name+" — "+t.minutes+" min";li.querySelector("button").onclick=()=>{tasks.splice(i,1);render()};list.appendChild(li)});document.getElementById("plannerSummary").textContent=tasks.length+" task"+(tasks.length===1?"":"s")+" · "+tasks.reduce((s,t)=>s+t.minutes,0)+" minutes"};document.getElementById("addTask").onclick=()=>{const name=document.getElementById("taskName").value.trim(),minutes=Number(document.getElementById("taskMinutes").value);if(!name||!Number.isFinite(minutes)||minutes<=0){message("Enter a task and a positive number of minutes.");return}tasks.push({name,minutes:Math.round(minutes)});document.getElementById("taskName").value="";document.getElementById("taskMinutes").value="";render();message("Task added.")};document.getElementById("clearTasks").onclick=()=>{tasks.length=0;render();message("List cleared.")}}
}
document.querySelectorAll(".tool-open").forEach(b=>b.addEventListener("click",()=>openTool(b.dataset.tool)));
const closeWorkspace=document.getElementById("closeWorkspace");if(closeWorkspace)closeWorkspace.addEventListener("click",()=>{workspace.hidden=true;document.getElementById("tools").scrollIntoView({behavior:"smooth"})});